version: '3.8'
services:
  database:
    container_name: postgres
    image: 'postgres:14.4-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=chuck-norris-db
    ports:
      - 5433:5432